/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness check */
    get: operations['health_api_v1_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/genres': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all genres
     * @description Return all genres. Small dataset — no pagination.
     */
    get: operations['list_genres_api_v1_genres_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/genres/{genre_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get genre by ID */
    get: operations['get_genre_api_v1_genres__genre_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/genres/{genre_id}/movies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List movies in a genre */
    get: operations['list_genre_movies_api_v1_genres__genre_id__movies_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/directors': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List directors */
    get: operations['list_directors_api_v1_directors_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/directors/{director_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get director by ID */
    get: operations['get_director_api_v1_directors__director_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/directors/{director_id}/movies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Movies by director */
    get: operations['list_director_movies_api_v1_directors__director_id__movies_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/actors': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List actors */
    get: operations['list_actors_api_v1_actors_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/actors/{actor_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get actor by ID */
    get: operations['get_actor_api_v1_actors__actor_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/actors/{actor_id}/movies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Movies by actor */
    get: operations['list_actor_movies_api_v1_actors__actor_id__movies_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/movies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List movies with filters */
    get: operations['list_movies_api_v1_movies_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/movies/{movie_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get movie by ID */
    get: operations['get_movie_api_v1_movies__movie_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/movies/{movie_id}/reviews': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List reviews for a movie */
    get: operations['list_reviews_api_v1_movies__movie_id__reviews_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ActorDetail
     * @description Full view with bio.
     */
    ActorDetail: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Birth Year */
      birth_year?: number | null;
      /** Bio */
      bio?: string | null;
    };
    /**
     * ActorRead
     * @description Compact view — used in lists and embedded in MovieDetail.
     */
    ActorRead: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Birth Year */
      birth_year?: number | null;
    };
    /**
     * DirectorDetail
     * @description Full view with bio. Returned on /directors/{id}.
     */
    DirectorDetail: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Birth Year */
      birth_year?: number | null;
      /** Bio */
      bio?: string | null;
    };
    /**
     * DirectorRead
     * @description Compact view — embedded in movie list and movie detail.
     */
    DirectorRead: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Birth Year */
      birth_year?: number | null;
    };
    /** Envelope[ActorDetail] */
    Envelope_ActorDetail_: {
      /** Success */
      success: boolean;
      data?: components['schemas']['ActorDetail'] | null;
      error?: components['schemas']['ErrorPayload'] | null;
      meta?: components['schemas']['Meta'] | null;
    };
    /** Envelope[DirectorDetail] */
    Envelope_DirectorDetail_: {
      /** Success */
      success: boolean;
      data?: components['schemas']['DirectorDetail'] | null;
      error?: components['schemas']['ErrorPayload'] | null;
      meta?: components['schemas']['Meta'] | null;
    };
    /** Envelope[GenreRead] */
    Envelope_GenreRead_: {
      /** Success */
      success: boolean;
      data?: components['schemas']['GenreRead'] | null;
      error?: components['schemas']['ErrorPayload'] | null;
      meta?: components['schemas']['Meta'] | null;
    };
    /** Envelope[MovieDetail] */
    Envelope_MovieDetail_: {
      /** Success */
      success: boolean;
      data?: components['schemas']['MovieDetail'] | null;
      error?: components['schemas']['ErrorPayload'] | null;
      meta?: components['schemas']['Meta'] | null;
    };
    /** Envelope[dict[str, str]] */
    Envelope_dict_str__str__: {
      /** Success */
      success: boolean;
      /** Data */
      data?: {
        [key: string]: string;
      } | null;
      error?: components['schemas']['ErrorPayload'] | null;
      meta?: components['schemas']['Meta'] | null;
    };
    /** Envelope[list] */
    Envelope_list_: {
      /** Success */
      success: boolean;
      /** Data */
      data?: unknown[] | null;
      error?: components['schemas']['ErrorPayload'] | null;
      meta?: components['schemas']['Meta'] | null;
    };
    /** Envelope[list[ActorRead]] */
    Envelope_list_ActorRead__: {
      /** Success */
      success: boolean;
      /** Data */
      data?: components['schemas']['ActorRead'][] | null;
      error?: components['schemas']['ErrorPayload'] | null;
      meta?: components['schemas']['Meta'] | null;
    };
    /** Envelope[list[DirectorRead]] */
    Envelope_list_DirectorRead__: {
      /** Success */
      success: boolean;
      /** Data */
      data?: components['schemas']['DirectorRead'][] | null;
      error?: components['schemas']['ErrorPayload'] | null;
      meta?: components['schemas']['Meta'] | null;
    };
    /** Envelope[list[GenreRead]] */
    Envelope_list_GenreRead__: {
      /** Success */
      success: boolean;
      /** Data */
      data?: components['schemas']['GenreRead'][] | null;
      error?: components['schemas']['ErrorPayload'] | null;
      meta?: components['schemas']['Meta'] | null;
    };
    /** Envelope[list[MovieRead]] */
    Envelope_list_MovieRead__: {
      /** Success */
      success: boolean;
      /** Data */
      data?: components['schemas']['MovieRead'][] | null;
      error?: components['schemas']['ErrorPayload'] | null;
      meta?: components['schemas']['Meta'] | null;
    };
    /** Envelope[list[ReviewRead]] */
    Envelope_list_ReviewRead__: {
      /** Success */
      success: boolean;
      /** Data */
      data?: components['schemas']['ReviewRead'][] | null;
      error?: components['schemas']['ErrorPayload'] | null;
      meta?: components['schemas']['Meta'] | null;
    };
    /** ErrorPayload */
    ErrorPayload: {
      /** Code */
      code: string;
      /** Message */
      message: string;
      /** Details */
      details?: {
        [key: string]: unknown;
      } | null;
    };
    /** GenreRead */
    GenreRead: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** Meta */
    Meta: {
      /** Request Id */
      request_id?: string | null;
      pagination?: components['schemas']['PaginationMeta'] | null;
    };
    /**
     * MovieDetail
     * @description Full detail view — adds synopsis, runtime, cast, and reviews.
     */
    MovieDetail: {
      /** Id */
      id: number;
      /** Title */
      title: string;
      /** Release Year */
      release_year: number;
      /** Poster Url */
      poster_url?: string | null;
      /** Average Rating */
      average_rating?: number | null;
      /**
       * Genres
       * @default []
       */
      genres: components['schemas']['GenreRead'][];
      director?: components['schemas']['DirectorRead'] | null;
      /** Synopsis */
      synopsis?: string | null;
      /** Runtime Minutes */
      runtime_minutes?: number | null;
      /**
       * Actors
       * @default []
       */
      actors: components['schemas']['ActorRead'][];
      /**
       * Reviews
       * @default []
       */
      reviews: components['schemas']['ReviewRead'][];
    };
    /**
     * MovieRead
     * @description Compact view for movie lists — includes genres and director for card display.
     */
    MovieRead: {
      /** Id */
      id: number;
      /** Title */
      title: string;
      /** Release Year */
      release_year: number;
      /** Poster Url */
      poster_url?: string | null;
      /** Average Rating */
      average_rating?: number | null;
      /**
       * Genres
       * @default []
       */
      genres: components['schemas']['GenreRead'][];
      director?: components['schemas']['DirectorRead'] | null;
    };
    /** PaginationMeta */
    PaginationMeta: {
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total */
      total: number;
      /** Total Pages */
      total_pages: number;
    };
    /** ReviewRead */
    ReviewRead: {
      /** Id */
      id: number;
      /** Movie Id */
      movie_id: number;
      /** Author Name */
      author_name: string;
      /** Rating */
      rating: number;
      /** Comment */
      comment: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_dict_str__str__'];
        };
      };
    };
  };
  list_genres_api_v1_genres_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_list_GenreRead__'];
        };
      };
    };
  };
  get_genre_api_v1_genres__genre_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        genre_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_GenreRead_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_genre_movies_api_v1_genres__genre_id__movies_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: never;
      path: {
        genre_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_list_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_directors_api_v1_directors_get: {
    parameters: {
      query?: {
        search?: string | null;
        sort?: string | null;
        page?: number;
        page_size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_list_DirectorRead__'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_director_api_v1_directors__director_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        director_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_DirectorDetail_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_director_movies_api_v1_directors__director_id__movies_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: never;
      path: {
        director_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_list_MovieRead__'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_actors_api_v1_actors_get: {
    parameters: {
      query?: {
        movie_id?: number | null;
        genre_id?: number | null;
        search?: string | null;
        sort?: string | null;
        page?: number;
        page_size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_list_ActorRead__'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_actor_api_v1_actors__actor_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        actor_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_ActorDetail_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_actor_movies_api_v1_actors__actor_id__movies_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: never;
      path: {
        actor_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_list_MovieRead__'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_movies_api_v1_movies_get: {
    parameters: {
      query?: {
        genre_id?: number | null;
        director_id?: number | null;
        actor_id?: number | null;
        year?: number | null;
        year_min?: number | null;
        year_max?: number | null;
        search?: string | null;
        sort?: string | null;
        page?: number;
        page_size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_list_MovieRead__'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_movie_api_v1_movies__movie_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        movie_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_MovieDetail_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_reviews_api_v1_movies__movie_id__reviews_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: never;
      path: {
        movie_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_list_ReviewRead__'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
